const icons = {
    user: require('./user.png'),
    password: require('./password.png'),
    folder: require('./folder.png'),
    arrow: require('./arrow.png'),
    arrowDark: require('./arrow_dark.png'),
    whiteCircule: require('./white_circule.png'),
    rightCircule: require('./right_circule.png'),
    taskBlue: require('./icon_task_blue.png'),
    taskGreen: require('./icon_task_green.png'),
    taskWhite: require('./icon_task_white.png'),
    taskDark: require('./icon_task_dark.png'),
    calendar: require('./calendar.png'),
    upload: require('./upload.png'),
    gallary: require('./gallary.png'),
    cross: require('./cross.png'),
    add: require('./add.png'),
    search: require('./search.png'),
    plus: require('./plus.png'),
    folderWhite: require('./folder_white.png'),
    searchGray: require('./search_gray.png'),
};
export default icons;
