const icons = {
    user: require('./user.png'),
    password: require('./password.png'),
    folder: require('./folder.png'),
    arrow: require('./arrow.png'),
    arrowDark: require('./arrow_dark.png'),
    whiteCircule: require('./white_circule.png'),
    rightCircule: require('./right_circule.png'),
    taskBlue: require('./icon_task_blue.png'),
    taskGreen: require('./icon_task_green.png'),
    taskWhite: require('./icon_task_white.png'),
    taskDark: require('./icon_task_dark.png'),
    calendar: require('./calendar.png'),
    upload: require('./upload.png'),
    gallary: require('./gallary.png'),
    cross: require('./cross.png'),
    delete: require('./delete.png'),
    add: require('./add.png'),
    search: require('./search.png'),
    plus: require('./plus.png'),
    folderWhite: require('./folder_white.png'),
    searchGray: require('./search_gray.png'),
    userWhite : require('./user_wite.png'),
    editUser: require('../../asserts/img/edit_user.png'),
    calenderWhite: require('./calender_white.png'),
    warningWhite: require('./warning_white.png'),
    clockWhite: require('./clock_white.png'),
    userWhiteProj: require('./user_white.png'),
    rightWhite: require('./right_white.png'),
    deleteWhite: require('./delete_white.png'),
    addGreen: require('./add_green.png'),
    editWhite: require('./edit_white.png'),
    taskUser: require('./task_user.png'),
    subTask: require('./sub_task.png'),
    calendarBlue: require('./calendar_blue.png'),
    clockOrange: require('./clock_orange.png'),
    noteRed: require('./note_red.png'),
    fileOrange: require('./file_orange.png'),
    chatBrown: require('./chat_brown.png'),
    forwordGray: require('./forword_gray.png'),
    closeRounded: require('./close_rounded.png'),
    deleteRoundRed: require('./delete_round_red.png'),
    editRoundWhite: require('./edit_round_white.png'),
    forwordGreen: require('./forword_green.png'),
};
export default icons;
