
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const GET_ALL_PROJECTS_BY_USER = 'GET_ALL_PROJECTS_BY_USER';
export const GET_ALL_PROJECTS_BY_USER_SUCCESS = 'GET_ALL_PROJECTS_BY_USER_SUCCESS';
export const GET_ALL_PROJECTS_BY_USER_FAILED = 'GET_ALL_PROJECTS_BY_USER_FAILED';

export const GET_ALL_TASK_BY_PROJECT = 'GET_ALL_TASK_BY_PROJECT';
export const GET_ALL_TASK_BY_PROJECT_SUCCESS = 'GET_ALL_TASK_BY_PROJECT_SUCCESS';
export const GET_ALL_TASK_BY_PROJECT_FAILED = 'GET_ALL_TASK_BY_PROJECT_FAILED';

export const GET_MY_TASK_BY_PROJECT = 'GET_MY_TASK_BY_PROJECT';
export const GET_MY_TASK_BY_PROJECT_SUCCESS = 'GET_MY_TASK_BY_PROJECT_SUCCESS';
export const GET_MY_TASK_BY_PROJECT_FAILED = 'GET_MY_TASK_BY_PROJECT_FAILED';

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILED = 'ADD_USER_FAILED';
export const ADD_USER_FAILED_MESSAGE = 'ADD_USER_FAILED_MESSAGE';

export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED';
export const EDIT_USER_FAILED_MESSAGE = 'EDIT_USER_FAILED_MESSAGE';

export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';

export const ADD_PROJECT = 'ADD_PROJECT';
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const ADD_PROJECT_FAILED = 'ADD_PROJECT_FAILED';

export const EDIT_PROJECT = 'EDIT_PROJECT';
export const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS';
export const EDIT_PROJECT_FAILED = 'EDIT_PROJECT_FAILED';



