
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const GET_ALL_PROJECTS_BY_USER = 'GET_ALL_PROJECTS_BY_USER';
export const GET_ALL_PROJECTS_BY_USER_SUCCESS = 'GET_ALL_PROJECTS_BY_USER_SUCCESS';
export const GET_ALL_PROJECTS_BY_USER_FAILED = 'GET_ALL_PROJECTS_BY_USER_FAILED';




